### ISSUE TITLE
i18n対応

### ISSUE THREAD

**Issue by Chipsnet** [BonyChops/Game-Console-Activity-to-Discord#9]
READMEが日本語対応してるならソースも日本語対応すべき

- [x] 言語選択機能
- [x] 言語ファイル作成
- [x] 言語読み込み機能

**Comment by Chipsnet** [comment]
[![Image from Gyazo](https://i.gyazo.com/0ca1afba437296e1be8fdd282bab99f4.png)](https://gyazo.com/0ca1afba437296e1be8fdd282bab99f4)

いい感じです

**Comment by BonyChops** [comment]
作るかあ～～～

**Comment by BonyChops** [comment]
とてもよいです
